version: "2.2"

services:
  mongo:
    image: mongo:3.4
    restart: always
    volumes:
      - mongodata:/data/db/
    ports:
      - 27017:27017

  web:
    scale: 4
    build: .
    env_file:
      - ./.env
    volumes:
      - ./build:/app/build
      - ./dist:/app/dist
    depends_on:
      - mongo

  nginx:
    image: nginx:latest
    depends_on:
      - web
      - mongo
    ports:
      - 80:80
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf

volumes:
  mongodata:
